use SANKHYA_TESTE
GO

SELECT
CASE WHEN (sankhya.AD_ROTEIROENTREGA.TIPMOV= 'V') THEN
(SELECT NF.NUMNOTA FROM sankhya.TGFCAB NF
WHERE NF.NUNOTA= sankhya.AD_ROTEIROENTREGA.NUNOTA)
ELSE (SELECT NF.NUMNOTA FROM sankhya.TGFCAB NF WHERE NF.NUNOTA=
(SELECT TOP(1) sankhya.TGFVAR.NUNOTA
FROM sankhya.TGFVAR WHERE NUNOTAORIG= sankhya.AD_ROTEIROENTREGA.NUNOTA)) END AS 'N_NOTA',
CASE WHEN (sankhya.AD_ROTEIROENTREGA.TIPMOV= 'V') THEN
(SELECT NF.DTNEG FROM sankhya.TGFCAB NF
WHERE NF.NUNOTA= sankhya.AD_ROTEIROENTREGA.NUNOTA)
ELSE (SELECT NF.DTNEG FROM sankhya.TGFCAB NF WHERE NF.NUNOTA=
(SELECT TOP(1) sankhya.TGFVAR.NUNOTA
FROM sankhya.TGFVAR WHERE NUNOTAORIG= sankhya.AD_ROTEIROENTREGA.NUNOTA)) END
AS 'DT_EMISSAO',
sankhya.AD_ROTEIROENTREGA.DTROTEIRO AS 'DT_ROTEIRO',
sankhya.AD_ROTEIROENTREGA.PREVENTREGA AS 'PREV_ENTREGA',
sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA AS 'DT_ENTREGA_TRANSPORTADORA',
ISNULL(sankhya.TGFPAR.AD_PZOTRANSPORTE,0) AS 'PZO_ENTREGA',
((CASE WHEN (sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA IS NULL)
THEN sankhya.AD_ROTEIROENTREGA.DTROTEIRO ELSE sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA END)
+ ISNULL(sankhya.TGFPAR.AD_PZOTRANSPORTE,0)) AS 'DT_PREVISTA_CLIENTE',
CONVERT(INT,(CONVERT(DATETIME,CONVERT(DATE,GETDATE())) -
((CASE WHEN (sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA IS NULL)
THEN sankhya.AD_ROTEIROENTREGA.DTROTEIRO ELSE sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA END)
+ ISNULL(sankhya.TGFPAR.AD_PZOTRANSPORTE,0)))) AS 'DIAS_ATRASO',
CONVERT(DATETIME,CONVERT(DATE,GETDATE())) AS 'DT_HOJE',
LTRIM(RTRIM(sankhya.AD_ROTEIROENTREGA.PARCEIRO)) AS 'PARCEIRO',
'REPRESENTANTE'= (SELECT LTRIM(RTRIM(V.APELIDO))+' - '+CONVERT(VARCHAR,V.CODVEND)
FROM sankhya.TGFVEN V WHERE V.CODVEND= sankhya.TGFCAB.CODVEND),
LTRIM(RTRIM(sankhya.AD_ROTEIROENTREGA.TRANSPORTADORA)) AS 'TRANSPORTADORA',
(REPLACE(REPLACE(LTRIM(RTRIM(CONVERT(VARCHAR(MAX),sankhya.AD_ROTEIROENTREGA.OBSERVACAO)))
, CHAR(13) + CHAR(10), ''), CHAR (10), '')) AS 'OBSERVACAO'

FROM sankhya.AD_ROTEIROENTREGA
JOIN sankhya.TGFCAB ON (sankhya.AD_ROTEIROENTREGA.NUNOTA= sankhya.TGFCAB.NUNOTA)
JOIN sankhya.TGFPAR ON (sankhya.TGFCAB.CODPARC= sankhya.TGFPAR.CODPARC)

WHERE CONVERT(DATE,sankhya.AD_ROTEIROENTREGA.DTROTEIRO) >= '01/06/2024'
AND CONVERT(DATE,sankhya.AD_ROTEIROENTREGA.DTROTEIRO) < CONVERT(DATE,GETDATE())
AND sankhya.AD_ROTEIROENTREGA.DTENTREGACLIENTE IS NULL
AND (CONVERT(INT,(CONVERT(DATETIME,CONVERT(DATE,GETDATE())) -
((CASE WHEN (sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA IS NULL) THEN sankhya.AD_ROTEIROENTREGA.DTROTEIRO ELSE sankhya.AD_ROTEIROENTREGA.DTTRANSPORTADORA END)
+ ISNULL(sankhya.TGFPAR.AD_PZOTRANSPORTE,0))))) >= 5

ORDER BY 8 DESC, 1